# Generated by Django 5.0.4 on 2024-06-28 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Manufacturer', models.CharField(blank=True, max_length=100)),
                ('Cures', models.CharField(blank=True, max_length=30)),
                ('SideEffects', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='BioText',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='DateOfBirth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Collected', models.BooleanField(default=False)),
                ('CollectedApproved', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.medicine')),
            ],
        ),
    ]
